### PR TITLE
New refactored

### PR DESCRIPTION
**Pull request by 0silverback0**
take a look at the code I changed and let me know if I did what you were expecting. If you wanted it to look like the image at the top of the issue I can do that for you as well, and if there is anything else you may need help with just let me know. Also your api key should go in a hidden file such as .env and then that file should be added to a .gitignore file. If any of this is not making sense just reach out.

### CODE REVIEW

**Comment by SAJ33L** [comment]
Man, I really appreciate the work you have done, it is really good, Actually I was planning to do it all by myself after my exams but you have done it all thanks a lot.

**Comment by 0silverback0** [comment]
Ok no problem at all! If you want me to do anything else or you get stuck again just let me know!

**Comment by SAJ33L** [comment]
The api_key is not being retried from the .env file can you help me with it?

**Comment by 0silverback0** [comment]
Fetch the changes so that you have them locally.

Then in the terminal run ``` pip install -r requirements.txt ``` this will install the dependencies in the requirements.txt file, which holds python-dotenv which allows for the data from the .env file to be read. 

Make sure you add your api key to your .env file like this API_KEY=your_api_key.

Once you have it working locally push your changes then go to the GitHub repo and delete the .env file as it should not be included in the repo which is why it's listed in the .gitignore file.

Let me know if there is any other troubles!

**Pull request merged**
